version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: "misc"
    labels:
      - "Action: no bump"
